var words = [
[
	"hurdling/n.跨栏运动",
	"boxing/n.拳击",
	"hula hooping/玩呼啦圈",
	"pogo stick jumping/弹簧单高跷游戏",
	"jumping jack/跳爆竹",
	"somersaulting/n.翻筋斗",
	"lunge/n.＆v.刺;跃进;前冲",
	"Guinness Book of World Records/《吉尼斯世界纪录大全》",
	"approximate/adj.近似的;大概的",
	"approximately/adv.远似地;大约地",
	"conventional/adj.习俗的;传统的",
	"laughter/笑;笑声",
	"reality/n.真实;事实",
	"in reality/实际上;现实",
	"adjustment/n.调整;调节",
	"tough/adj.强硬的;困难的",
	"extreme/adj.极端的;偏激的",
	"vomit/呕吐n.呕吐;呕吐物",
	"gymnastics/n.体操;体能训练",
	"gymnastics/adv.体能训练方面",
	"unfit/adj.不适宜的;不太健康的",
	"fascinate/vt.使着迷;入迷",
	"meditation/n.沉思;冥想",
	"spiritual/adj.精神上的",
	"marathon/n.马拉松赛跑",
	"urge/vt.催促;力劝",
	"accomplish/vt.完成;实现",
	"motivation/n.动机",
	"devotion/n.热爱;投入",
	"soul/n.灵魂;心灵;精神",
	"sacred/adj.宗教的;庄严的;神圣的",
	"deed/n.行为;功绩",
	"conception/n.主意;计划",
	"tact/n.机敏;乖巧;老练;技巧",
	"regret/vt.＆vi.后悔;感到抱歉",
	"repentance/n.后悔",
	"wisdom/n.智慧",
	"virtue/n.美德",
	"noble/adj.高尚的;贵族的",
	"doom/vt.注定;判决",
	"bid/vt.＆vi出价;投标",
	"juggle/vt.＆Vi.耍把戏;玩杂耍",
	"triathlon/n.三项全能运动",
	"triathlete/n.三项全能运动员",
	"amateur/n.业余爱好者",
	"champion/n.冠军;优胜者",
	"therefore/adv.因此;所以",
	"springboard/n.跳板",
	"economics/n.经济学",
	"entire/adj.全部的;完整的",
	"attain/vt.达到;获得",
	"profile/n.(人物或事物之)简介;侧面,轮廓",
	"courageous/adj.勇敢的;有胆量的",
	"appreciate/vt.鉴赏;感激",
	"appreciation/n.感谢;感激;欣赏",
	"accountant/n.会计",
	"receptionist/n.招待员;接待员",
	"lawyer/n.律师",
	"politician/n.政治家;政客",
	"scarf/n.围巾;头巾;领巾",
	"zip/n.拉链",
	"underwear/n.内衣裤",
	"overcoat/n.外套大衣;长大衣",
	"salary/n.薪水",
	"wage/n.工资"
], [
	"latitude/n.纬度",
	"voyage/n.航海;航行",
	"mercy/n.仁慈;宽恕;怜悯",
	"at the mercy of/受……支配",
	"encyclopedia/n.百科全书",
	"alongside/prep.靠着;沿着adv.在旁边,沿着边",
	"exploration/n.探险;探测",
	"minimum/adj.最小的;最低的",
	"celestial/adj.天上的",
	"pole/n.地极;柱;杆",
	"equator/n.赤道",
	"horizon/n.地平线;视野",
	"overhead/adj.在头上的",
	"seaweed/n.海草;海藻",
	"nowhere/adv.离岸的;海面上的",
	"outward/adj.外面的;向外的",
	"tide/n.潮;潮汐;潮流;趋势",
	"secure/adj.安全的;可靠的",
	"knot/n.结 vt.打结",
	"log/n.原木;木材;航行日志",
	"nautical/adj.海上的;航海的",
	"nautical mile/海里",
	"magnetic/adj.磁的;有磁性的",
	"bearing circle/方位圆",
	"random/adj.任意的;随便的",
	"astrolabe/n.古代的天体观测仪;星盘",
	"awkward/adj.难使用的;笨拙的",
	"reference/n.参考",
	"quadrant/n.象限;四分仪",
	"precise/adj.精确的;准确的",
	"simplify/vt.单一化;简单化",
	"portable/adj.轻便的;手提的;便携的",
	"shortcoming/n.缺点;短处",
	"sextant/n.六分仪",
	"update/vt.更新",
	"tendency/n.趋向;倾向",
	"reliable/adj.可靠的;可信赖的",
	"Samuel/塞缪尔",
	"swoop/vi.突降;猛扑",
	"parcel/n.小包;包裹",
	"peck/vt.＆vi.啄食",
	"cliff/n.悬崖;峭壁",
	"expedition/n.远征;探险(队)",
	"compulsory/adj.必须做的;必修的",
	"reform/n.改革;革新",
	"survival/n.生存;幸存",
	"incident/n.事件;事变",
	"departure/n.出发;离开",
	"crew/n.(轮船飞机等上的)工作人员,(工作)队",
	"deposit/vt.放;(把钱)存入银行",
	"dilemma/n.进退两难的局面",
	"drawback/n.缺点;障碍",
	"dusk/n.薄暮;黄昏",
	"routine/n.常规;日常事务",
	"reckon/vt.计算;估计",
	"reckoning/n.计算;估计",
	"starvation/n.挨饿;饿死",
	"psychology/n.心理学",
	"psychologically/adv.心理上地;心理学地",
	"tension/n.紧张;不安;张力",
	"gradual/adj.逐渐的;逐步的",
	"gradually/adv.逐渐地;逐步地",
	"foresee/vt.预见;预知",
	"thirst/n.渴;口渴",
	"set loose/出发;开始",
	"tear/vt.扯破;撕破",
	"hardship/n.困苦;艰难",
	"jaw/n.颚;颌;下巴",
	"jaws of death/鬼门关;死神",
	"roar/vt.＆Vi.咆哮;轰鸣",
	"background/n.背景;后台"
], [
	"associate/vt.使发生联系;使联合;结交",
	"associate with/与……联系",
	"barrier/n.障碍物;栅栏;屏障",
	"Great Barrier Reef/大堡礁",
	"brochure/n.(作介绍或宣传用的)小册子",
	"Commonwealth/n.国家;共和国;联邦",
	"Oceania/n.大洋洲",
	"adequate/adj.适当的;足够的",
	"ecology/n.生态学;生态",
	"autonomous/adj.自治的",
	"federal/adj.朕邦的;联合的;联邦制的",
	"defence/n.防卫;辩护",
	"policy/n.政策;方针",
	"tax/n.税;税款",
	"taxation/n.征税;税款",
	"nation/n.国家;民族",
	"citizen/n.市民;公民",
	"citizenship/n.公民身份;公民的职责和权力",
	"celebration/n.庆祝;庆典",
	"birthplace/n.诞生地",
	"tolerance/n.宽容;忍受",
	"migrant/n移居者;移民;候鸟",
	"homeland/n.祖国;本国",
	"via/vi:经;通过;经由",
	"superb/adj.卓越的;杰出的;极好的",
	"rust/n.铁锈",
	"rusty/adj.生锈的;铁锈色的",
	"tropical/adj.热带的",
	"splendour/n.壮丽;杰出;壮观",
	"timetable/n.时间表;时刻表",
	"heritage/n.遗产;继承物",
	"aboriginal/adj.土著的;土生的n.土著居民",
	"out of respect/出于尊敬",
	"fortnight/n.两星期",
	"reservation/n.保留;预定",
	"highway/n.公路;大路;(美)高速公路",
	"cradle/n.摇篮;发源地",
	"rainfall/n.降雨;降雨量",
	"agriculture/n.农业;农耕",
	"sow/vt.＆vi播种;传播",
	"bachelor/n.单身汉;(文理)学士",
	"correspond/vi.通信;符合",
	"correspond with/与……通信",
	"owe/vt.＆vi.感激;欠(债等)",
	"owe...to/把……归功于;",
	"enclosure/n.围地;(用于特定目的的)围场",
	"authority/n.权力;权威;当局",
	"desperate/adj.不顾一切的;绝望的",
	"shrink/vt.＆vi.收缩;(使)皱缩 ;缩短",
	"barbecue/n.金属烤架;烧烤野餐",
	"talk...into.../说服某人做某事",
	"wind/vt.绕;缠",
	"limb/n.肢;翼;分支",
	"venom/n.毒液;恶意;怨恨",
	"venomous/adj.有毒的;分泌毒液的",
	"anti-venom/抗毒",
	"paralyze/vt.使瘫痪;使麻痹",
	"sickness/n.疾病;恶心",
	"recover/vt.＆vi.痊愈;复原",
	"funnel/n.漏斗",
	"funnelweb spider/漏斗网蜘蛛",
	"snatch/vt.攫取;抢走",
	"amongst/prep.在……中间;在……之中",
	"vinegar/n.醋",
	"unconscious/adj.不省人事;未发觉的;无意识的"
],  [
	"pollinate/vt.对……授粉",
	"pollinator/n.虫媒",
	"courtyard/n.庭院;院子;天井",
	"balcony/n.阳台;包厢",
	"exotic/adj.异国情调的;外来的;奇异的",
	"date back to/追溯到;远在……年代",
	"distant/adj.远的;远处的",
	"Egypt/n.埃及",
	"goods/n.货物",
	"scale/n.磅秤;天平盘",
	"conflict/n.斗争;冲突",
	"missionary/adj.教会的;传教的n.传教士",
	"Joseph Banks/约瑟夫-班克斯",
	"endeavour/n.尽力;竭力",
	"anchor/n.锚vt.抛锚,锚定",
	"tight/adj.紧的;紧密的",
	"tightly/adv.紧紧地;坚固地",
	"seal/vt.封闭;密封",
	"container/n.容器",
	"restriction/n.限制;约束",
	"fluency/n.流利;流畅",
	"shave/vt.＆vi.剃;刮",
	"thunderstorm/n.雷雨;雷暴",
	"pirate/n.海盗",
	"appeal/vi(对某人)有吸引力;求助",
	"appeal to being attractive/(对某人)有吸引力;呼吁",
	"dove/n.鸽子",
	"botanist/n.植物学家",
	"chrysanthemum/n.菊花",
	"red date/红枣",
	"lower/vt.降低;跌落;减弱",
	"beard/n.胡须",
	"ripe/adj.熟的;成熟的",
	"irrigation/n.灌溉",
	"weed/n.野草;杂草",
	"spear/n.矛;标枪",
	"string/n.线;细绳;一串",
	"spade/n.铲;铁锹",
	"postpone/vt.推迟;延迟",
	"pyramid/n.金字塔",
	"monument/n.纪念碑",
	"pitcher/n.猪笼草",
	"Rafflesia arnoldii/n.大王花",
	"rot/vt.＆vi腐烂;腐败",
	"evolve/vt.＆vi发展;进展;进化",
	"evolution/n,演变;进化",
	"nectar/n.花蜜;甘露",
	"attach/vt.缚上;系上;附加",
	"attach to/贴上;附上",
	"wasp/n.黄蜂",
	"beetle/n.甲虫",
	"bat/n.蝙蝠",
	"moth/n.蛾",
	"humming-bird/n.蜂鸟",
	"typical/adj典型的;有代表性的",
	"petal/n.花瓣",
	"tube/n.管;管子",
	"delicate/adj.精巧的;脆弱的;微妙的",
	"fragrant/adj.芬芳的;香的",
	"daisy/n.雏菊",
	"odour/n.气味;香味;臭味",
	"odourless/adj.没有气味的;无嗅的",
	"give out/发出(气味,热等);分发",
	"dull/adj.不鲜明的;阴暗的",
	"musty/adj.发霉的;有霉味的",
	"fruity/adj.果味的;(酒)有葡萄味的",
], [
	"billboard/n.(户外)布告板;广告牌",
	"casual/adj.偶然的;随意的;临时的",
	"garment/n.衣服;外衣",
	"turn...into/(使)变成",
	"advertiser/n.登广告者;广告客户",
	"advert/n.广告",
	"inform/通知,告诉",
	"association/n.协会;联系;关联",
	"target/n.目标;对象;靶子",
	"fit into/适合",
	"basis/n.基础;根据",
	"technique/n.技术;技巧",
	"lane/n.车道,行车线",
	"feature/n.特征;容貌;特色;特写vt.vi.以……为特色,特写",
	"conscience/n.良心;道德心",
	"worthy/adj.有价值的;可敬的",
	"corporation/,n.公司;法人;社团 budget/n.预算",
	"expense/n.费用;代价",
	"broadcast/n.广播;播音vt.vi.广播,播放,播送",
	"rely/vi.依赖;信赖",
	"rely on/依赖;依靠",
	"visual/adj.看的;视觉的",
	"generate/vt.产生;发生",
	"response/n.回答;响应;反应",
	"stereo/n.立体声;立体声器材",
	"have no use for/不需要;厌恶;对……不耐烦,讨厌",
	"refresh/vt.使(精神)振作;使恢复;更新",
	"partly/adv.部分;在一定程度上",
	"murder/vt.谋杀;谋杀案",
	"suitcase/n.手提箱;衣箱",
	"sheet/n.片;张;薄片;被单",
	"actress/n.女演员",
	"typist/n.打字员",
	"spokesman/n.发言人",
	"fluent/adj.流利的;流畅的",
	"hostess/n.女主人",
	"invitation/n.邀请",
	"appoint/vt.约定;指定;任命",
	"chairman/n.主席",
	"raise/vt.筹集;提高;饲养",
	"dial/vt.拨(号)",
	"operator/n.操作员;接线员",
	"litre/n.升",
	"mature/adj.成熟的;到期的",
	"fashion/,n.样式;流行;时尚",
	"misleading/adj.易误解的;令人误解的",
	"dishonest/adj.不诚实的",
	"alcoholic/adj.酒精的;含酒精的n.酗酒者,酒鬼",
	"tobacco/n.烟草;烟草制品",
	"ban/n.禁令 vt.禁止;取缔",
	"promote/vt.促进;提升",
	"immoral/adj.不道德的;邪恶的",
	"decent/adj.正派的;得体的;适当的",
	"ethics/n.伦理学;道德规范",
	"ethical/adj.合乎道德的;道德的",
	"offending/adj.令人不愉快的;伤害人的感情的",
	"beware/vi.小心;谨防",
	"consumer/n.消费者;顾客",
	"trustworthy/adj.可信赖的;可靠的"
]]