var all =
 new Array(new block("我的收藏", "shoucang",
 new Array()),
 new block("学习工具", "xuexi",
 new Array(new link("http://www.chengyujielong.com.cn/", "成语接龙"),
 new link("http://jfc120.com/", "在线解方程"),
 new link("https://www.desmos.com/calculator", "绘制数学函数"),
 new link("https://grammarchecker.net/", "检测语法"),
 new link("https://www.chemicalaid.com/tools/equationbalancer.php", "配平方程式"),
 new link("http://www.gaokao.com/", "高考网"),
 new link("https://gkcx.eol.cn", "高考数据库"),
 new link("https://hanyu.baidu.com/", "百度汉语"),
 new link("http://fanyi.baidu.com", "百度翻译"),
 new link("http://baike.baidu.com", "百度百科"),
 new link("https://haoxue.baidu.com/", "百度好学"))),
 new block("实用工具", "gongjv",
 new Array(new link("https://www.onlineocr.net/zh_hans/", "在线 OCR"),
new link("https://www.wechat2pdf.com/", "公众号转 PDF"),
 new link("https://smallpdf.com/cn", "玩转 PDF"),
 new link("http://www.qiuziti.com/", "在线字体识别"),
 new link("https://zhuanhuan.supfree.net/", "格式转换"),
 new link("https://tool.lu/hexconvert", "进制转换"),
 new link("https://tool.lu/morse", "摩斯电码"),
 new link("https://tool.lu/encdec", "加密解密"),
 new link("http://www.bejson.com/convert/unicode_chinese/", "中文 Unicode"),
 new link("https://tool.lu/hexstr/", "十六进制字符串"),
 new link("https://zwfw.mps.gov.cn", "重名查询"),
 new link("https://chp.shadiao.app/", "彩虹屁生成器"),
 new link("https://zuanbot.com/", "骂人宝典"),
 new link("https://pyq.shadiao.app/", "文案生成器"),
 new link("https://suulnnka.github.io/BullshitGenerator/index.html", "文章生成器"),
 new link("https://paintschainer.preferred.tech/index_zh.html", "AI 上色"),
 new link("https://igfonts.io/", "英文字体生成器"),
 new link("https://tools.miku.ac/screen_clock/", "时钟屏保"),
 new link("https://tools.catiz.cn/t/lptime/", "创意时钟"),
 new link("https://tools.miku.ac/random/", "随机数生成"),
 new link("https://tools.miku.ac/lifecount/", "人生小格"),
 new link("https://tool.lu", "更多工具"))),
 new block("媒体相关", "meiti",
 new Array(new link("https://music.163.com/", "网易云音乐"),
 new link("http://www.kugou.com/", "酷狗音乐"),
 new link("https://y.qq.com/", "QQ 音乐"),
 new link("http://xiuxiu.web.meitu.com/", "美图秀秀"),
 new link("http://www.uupoop.com/", "在线 PS"),
 new link("http://image.baidu.com", "百度图片"),
 new link("http://image.baidu.com/?fr=shitu", "百度识图"),
 new link("http://m.photofunia.com", "图片合成"),
 new link("https://wallhaven.cc/", "高清壁纸下载"),
 new link("https://www.qijishow.com/", "奇迹秀"),
 new link("https://ibaotu.com/", "包图网"),
 new link("http://699pic.com/", "摄图网"),
 new link("https://www.58pic.com/", "千图网"),
 new link("https://www.iconfont.cn/search/index", "阿里巴巴图标库"),
 new link("https://imgchr.com/", "路过图床"),
 new link("https://www.qt86.com/", "艺术字生成"),
 new link("https://www.iqiyi.com", "爱奇艺"),
 new link("http://www.youku.com", "优酷"),
 new link("https://v.qq.com", "腾讯视频"),
 new link("https://www.bilibili.com", "哔哩哔哩"),
 new link("https://www.ximalaya.com", "喜马拉雅"))),
 new block("游戏娱乐", "youxi",
new Array(new link("http://www.rubik.com.cn/", "魔方小站"),
 new link("https://vigorouspro.github.io/hamburgerburger", "汉堡包"),
 new link("https://ddiu8081.github.io/oreooo/", "奥利奥"),
 new link("http://www.7k7k.com/", "7K7K"),
 new link("http://www.4399.com/", "4399"),
 new link("http://duilian.msra.cn/app/couplet.aspx", "对对联"),
 new link("https://m.fontke.com/tool/image2ascii", "图片转字符画"))),
 new block("交通出行", "tianqi",
 new Array(new link("http://www.weather.com.cn/air/", "空气质量"),
 new link("http://www.weather.com.cn/weather1dn/101060101.shtml", "天气预报"),
 new link("https://clr9t.com/pages/lightpollution/", "光污染"),
 new link("https://tool.lu/coordinate/", "地图坐标系"),
 new link("http://map.baidu.com/", "百度地图"),
 new link("https://www.amap.com/", "高德地图"),
 new link("https://www.google.com/maps", "谷歌地图"),
 new link("https://map.qq.com/", "腾讯地图"),
 new link("https://www.qyer.com/", "穷游网"))),
 new block("编程开发", "daima",
 new Array(new link("http://noi.openjudge.cn/", "Openjudge"),
 new link("https://tool.lu/html", "HTML 美化工具"),
 new link("https://tool.lu/css", "CSS 美化工具"),
 new link("https://tool.lu/js", "JS 美化工具"),
 new link("https://tool.lu/color/", "颜色转换"),
 new link("https://flatuicolors.com/", "常用颜色"),
 new link("https://www.csdn.net", "CSDN论坛"),
 new link("http://tool.oschina.net/apidocs", "在线文档"),
 new link("https://www.luogu.org/training/mainpage", "洛谷"),
 new link("http://github.com", "Github"),
 new link("http://www.runoob.com/", "菜鸟教程"),
 new link("http://www.w3school.com.cn/index.html", "W3School"),
 new link("https://c.runoob.com/", "在线编程"),
 new link("https://www.ratatype.com/", "打字练习"))),
 new block("网站相关", "fankui",
 new Array(new link("html/setting.html?url=" + window.location.href, "网站设置"),
 new link("https://www.jianshu.com/p/bc906dffa963", "网站介绍"),
 new link("https://wj.qq.com/s2/3808169/f7d3/", "反馈建议"))));
